#!/bin/bash
pulp browserify -j 4 -O > assets/bundle.js

#1. minify:
uglifyjs assets/bundle.js --noerr --screw-ie8 -c -m > assets/bundle.min.js
#rm assets/bundle.js

#2 dont minify:
#mv out.js assets/bundle.js
